on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 'stable','10', '8' ]
    name: Node ${{ matrix.node }} Tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Npm Install
        run: npm ci
      - name: Run Lint
        run: npm run test:lint
      - name: Run Build
        run: npm run test:build
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Create Docs
        run: npm run test:docs