name: Test and Publish
on: [push,pull_request]

jobs:
  test_suite:
    name: Test - ${{ matrix.os }} - Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Deps
        run: |
          npm ci
          npm install --no-save @donmahallem/trapeze-api-types
      - name: Run Build
        run: npm run build
      - name: Run Test
        run: npm run test:ci
      - name: Run Lint
        run: npm run lint
      - name: Run Docs
        run: npm run docs
      - name: Coveralls Coverage Upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: matrix.os == 'ubuntu-latest' && matrix.node == 12
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
  finish_coverage:
    name: Finish Coverage Upload
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true